In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set display option to avoid scientific notation in pandas, show up to 5 decimal points
pd.set_option('display.float_format', lambda x: '%.5f' % x)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

In [3]:
# Load the dataset 
flood_data = pd.read_excel("flood_full_data.xlsx")
flood_data.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,Country,Subregion,Region,Location,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2018-0040-BRA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),DFO:4576,NaN,BRA,Brazil,Latin America and the Caribbean,Americas,Rio de Janeiro,Heavy rains,Collapse|Flood,No,No,No,NaN,55138.9500,Km2,-22.4790,-44.0950,NaN,2018,2.0000,14.0000,2018,2.0000,16.0000,4.0000,NaN,250.0000,NaN,250.0000,NaN,NaN,NaN,NaN,10000.0000,12492.0000,80.0496,"[{""adm2_code"":9961,""adm2_name"":""Rio De Janeiro""}]","[{""gid_2"":""BRA.19.68_2"",""migration_date"":""2025...",2018-02-20,2025-12-20
1,2022-0770-RWA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,RWA,Rwanda,Sub-Saharan Africa,Africa,Kigali,NaN,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2022,11.0000,17.0000,2022,11.0000,18.0000,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.2946,"[{""adm1_code"":21970,""adm1_name"":""Kigali City/U...","[{""gid_1"":""RWA.5_1"",""migration_date"":""2025-12-...",2022-11-25,2025-12-20
2,2000-0620-NGA,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,NaN,NaN,NGA,Nigeria,Sub-Saharan Africa,Africa,Lagos province,Brief torrential rain,NaN,No,No,No,NaN,7700.0000,Km2,NaN,NaN,NaN,2000,9.0000,20.0000,2000,9.0000,21.0000,NaN,NaN,500.0000,NaN,500.0000,NaN,NaN,NaN,NaN,4805.0000,8753.0000,54.8952,"[{""adm1_code"":2230,""adm1_name"":""Lagos""}]","[{""gid_1"":""NGA.25_1"",""migration_date"":""2025-12...",2005-09-15,2025-12-20
3,2022-0405-PAK,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2022-000270,NaN,PAK,Pakistan,Southern Asia,Asia,"Lasbela, Jhal Magsi, Killa Saifullah, Pishin, ...",Monsoon rain,"Slide (land, mud, snow, rock)|Storm",No,Yes,Yes,NaN,NaN,Km2,NaN,NaN,NaN,2022,6.0000,14.0000,2022,9.0000,14.0000,1739.0000,12865.0000,33000000.0000,NaN,33012865.0000,10000000.0000,10718733.0000,7000.0000,7503.0000,15000000.0000,16078100.0000,93.2946,NaN,NaN,2022-07-07,2023-09-26
4,2022-0347-CIV,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2022-000249,NaN,CIV,Côte d’Ivoire,Sub-Saharan Africa,Africa,"Abobo, Anyama, Attecoubé, Bingerville, Port-Bo...",Heavy rains,"Slide (land, mud, snow, rock)",No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2022,6.0000,16.0000,2022,6.0000,21.0000,13.0000,114.0000,11478.0000,NaN,11592.0000,NaN,NaN,NaN,NaN,NaN,NaN,93.2946,NaN,NaN,2022-06-29,2023-09-26

In [4]:
flood_data.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group', 'Disaster Subgroup', 'Disaster Type',
       'Disaster Subtype', 'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin',
       'Associated Types', 'OFDA/BHA Response', 'Appeal', 'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year', 'Start Month', 'Start Day', 'End Year',
       'End Month', 'End Day', 'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected',
       'Reconstruction Costs ('000 US$)', 'Reconstruction Costs, Adjusted ('000 US$)', 'Insured Damage ('000 US$)',
       'Insured Damage, Adjusted ('000 US$)', 'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='object')

In [5]:
relevant_columns=['Disaster Type','Disaster Subtype','ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin','Associated Types','River Basin', 
                  'Start Year', 'Start Month', 'Start Day', 'End Year','End Month', 'End Day']

flood_pd=flood_data[relevant_columns].copy()


flood_pd['Start Date'] = pd.to_datetime(flood_pd[['Start Year', 'Start Month', 'Start Day']].rename(columns={'Start Year': 'year', 'Start Month': 'month', 'Start Day': 'day'}), errors='coerce')
flood_pd['End Date'] = pd.to_datetime(flood_pd[['End Year', 'End Month', 'End Day']].rename(columns={'End Year': 'year', 'End Month': 'month', 'End Day': 'day'}), errors='coerce')
flood_pd['Duration'] = (flood_pd['End Date'] - flood_pd['Start Date']).dt.days.astype('Int64')
#drop unnecessary columns
flood_pd.drop(columns=['Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day'], inplace=True)
#order flood by date soonest first
flood_pd.sort_values(by='Start Date', inplace=True, ascending=False)
#reset index
flood_pd.reset_index(drop=True, inplace=True)

flood_pd.head()

,Disaster Type,Disaster Subtype,ISO,Country,Subregion,Region,Location,Origin,Associated Types,River Basin,Start Date,End Date,Duration
0,Flood,Flood (General),SYR,Syrian Arab Republic,Western Asia,Asia,"Idleb, Lattaquié, Hama",Heavy rain,NaN,NaN,2026-02-08,2026-02-10,2
1,Flood,Flash flood,IDN,Indonesia,South-eastern Asia,Asia,Greater Jakarta area and the Indramayu regency...,Heavy rain,NaN,"Cilanang, Srenseng and Medana rivers",2026-01-28,2026-02-03,6
2,Flood,Flood (General),COL,Colombia,Latin America and the Caribbean,Americas,"Cordoba, Sucre, Cauca, La Guajira, Chocó, and ...",Torrential rain,NaN,Sinu river,2026-01-26,2026-02-11,16
3,Flood,Flood (General),TUN,Tunisia,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,NaN,2026-01-18,2026-01-21,3
4,Flood,Flood (General),DZA,Algeria,Northern Africa,Africa,"Laghouat, Blida, Djelfa, Mascara, El Bayadh, B...",Heavy rain,NaN,NaN,2026-01-18,2026-01-20,2

In [6]:
#flood for common crawl last 150 events
rel_columns=['ISO', 'Country', 'Subregion', 'Region', 'Location', 'River Basin', 'Start Date', 'End Date','Duration']
#use relevant columns
flood_crawl= flood_pd[rel_columns].iloc[:150].copy()
#save to csv
flood_crawl.to_csv('flood_crawl.csv', index=False)